# Generated by Django 4.0.4 on 2022-05-12 20:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=4), blank=True, size=None)),
                ('color', models.CharField(max_length=20)),
                ('fabric', models.ForeignKey(blank=True, default='none', on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productattribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.currency'),
        ),
    ]
